package com.cns.aidd_reservation.reservation.repository;

import java.util.List;

import com.cns.aidd_reservation.reservation.dto.*;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ReservationRepository {
	public RetrieveReservationOutDto retrieveReservation(RetrieveReservationInDto retrieveReservationInDto) throws Exception;
	public RetrieveSeatAvailableOutDto retrieveSeatAvailable(RetrieveSeatAvailableInDto retrieveSeatAvailableInDto) throws Exception;
	public RetrieveReservationBySeatTimeOutDto retrieveReservationBySeatTime(RetrieveReservationBySeatTimeInDto retrieveReservationBySeatTimeInDto) throws Exception;
	public List<RetrieveReservationHistoryListOutDto> retrieveReservationHistoryList(RetrieveReservationHistoryListInDto retrieveReservationBySeatTimeInDto) throws Exception;
	public RetrieveReservationByEmployeeOutDto retrieveReservationByEmployee(RetrieveReservationByEmployeeInDto retrieveReservationByEmployeeInDto) throws Exception;
	public RetrieveTotalTimeOutDto retrieveTotalTime(RetrieveTotalTimeInDto retrieveTotalTimeInDto) throws Exception;
	public List<RetrieveCurrentReservationOutDto> retrieveCurrentReservation(RetrieveCurrentReservationInDto retrieveCurrentReservationInDto) throws Exception;
	public int insertReservation(InsertReservationDto insertReservationDto) throws Exception;
	public int updateReservationStatus(UpdateReservationStatusDto updateReservationStatusDto) throws Exception;
	public int updateReservationSeat(UpdateReservationSeatDto updateReservationSeatDto) throws Exception;
	public int updateReservationTime(UpdateReservationTimeDto updateReservationTimeDto) throws Exception;

}
